// apps/web/app/components/ui/Sheet.vue
<script setup lang="ts">
import {
  DialogRoot,
  DialogPortal,
  DialogOverlay,
  DialogContent,
  DialogTitle,
  DialogDescription,
  DialogClose,
} from 'reka-ui';
import type { HTMLAttributes } from 'vue';
import { cn } from '~/lib/utils';

/**
 * MD3 modal side sheet: slides in from `side` (default right), 16dp outer
 * corners on the open edge, surface-container-low, plain scrim. Control with
 * `v-model:open`.
 */
const props = withDefaults(
  defineProps<{
    title: string;
    description?: string;
    side?: 'right' | 'left';
    class?: HTMLAttributes['class'];
  }>(),
  { side: 'right' },
);

const open = defineModel<boolean>('open', { default: false });
</script>

<template>
  <DialogRoot v-model:open="open">
    <DialogPortal>
      <DialogOverlay class="fixed inset-0 z-50 bg-scrim" />
      <DialogContent
        :class="
          cn(
            'fixed inset-y-0 z-50 flex w-[calc(100%-3rem)] max-w-sm flex-col bg-surface-container-low shadow-theme-lg focus:outline-none',
            side === 'right'
              ? 'right-0 rounded-l-2xl data-[state=open]:animate-[slide-in-right_250ms_cubic-bezier(0.05,0.7,0.1,1)]'
              : 'left-0 rounded-r-2xl data-[state=open]:animate-[slide-in-left_250ms_cubic-bezier(0.05,0.7,0.1,1)]',
            props.class,
          )
        "
      >
        <div
          class="mb-5 flex items-start justify-between gap-4 border-b border-outline-variant p-5"
        >
          <div class="space-y-1">
            <DialogTitle class="text-base font-semibold text-on-surface">{{ title }}</DialogTitle>
            <DialogDescription v-if="description" class="text-sm text-on-surface-variant">
              {{ description }}
            </DialogDescription>
          </div>
          <DialogClose
            class="touch-target relative rounded-full p-2 text-on-surface-variant transition-colors hover:bg-on-surface-variant/10 hover:text-on-surface"
            aria-label="Close"
          >
            <MaterialSymbol name="close" :size="20" />
          </DialogClose>
        </div>
        <div class="flex-1 overflow-y-auto overscroll-contain p-5 text-sm text-on-surface">
          <slot />
        </div>
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>

// apps/web-next/components/ui/sheet.tsx
'use client';

import { cn } from '@/lib/utils';
import { X } from 'lucide-react';
import { useEffect, type ReactNode } from 'react';

/**
 * Right-side sheet (port of the Nuxt variant's Sheet surface): the filter
 * panel container. Slide-in from the right (keyframes in globals.css),
 * closable with Escape and the scrim.
 */
export function Sheet({
  open,
  onOpenChange,
  title,
  description,
  children,
  className,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  title: string;
  description?: string;
  children: ReactNode;
  className?: string;
}) {
  useEffect(() => {
    if (!open) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onOpenChange(false);
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onOpenChange]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[60]">
      <div
        className="absolute inset-0 animate-[fade-in_150ms_ease-out] bg-scrim"
        onClick={() => onOpenChange(false)}
        aria-hidden="true"
      />
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="sheet-title"
        className={cn(
          'absolute inset-y-0 right-0 flex w-80 max-w-[85vw] animate-[slide-in-right_300ms_var(--ease-emphasized-decelerate)] flex-col bg-surface-container-low shadow-theme-lg',
          className,
        )}
      >
        <div className="flex items-start justify-between gap-4 border-b border-outline-variant p-5">
          <div>
            <h2 id="sheet-title" className="text-base font-semibold text-on-surface">
              {title}
            </h2>
            {description && <p className="mt-1 text-xs text-on-surface-variant">{description}</p>}
          </div>
          <button
            type="button"
            className="touch-target relative flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-on-surface-variant/10 hover:text-foreground"
            aria-label="Close"
            onClick={() => onOpenChange(false)}
          >
            <X size={18} aria-hidden="true" />
          </button>
        </div>
        <div className="flex-1 overflow-y-auto p-5">{children}</div>
      </div>
    </div>
  );
}
