// apps/web/app/components/ui/Tabs.vue
<script setup lang="ts">
import { TabsRoot, TabsList, TabsTrigger, TabsContent } from 'reka-ui';
import type { HTMLAttributes } from 'vue';
import { cn } from '~/lib/utils';

export interface TabDef {
  value: string;
  label: string;
  /** Lucide icon name (optional). */
  icon?: string;
}

/**
 * MD3 primary tabs: fixed top row on the page/content, active tab colored
 * primary with a 3dp bottom indicator and semibold label, label-large
 * typography. Panel content per tab comes from the `#tab-{value}` slots.
 */
const props = defineProps<{
  tabs: TabDef[];
  class?: HTMLAttributes['class'];
}>();

const model = defineModel<string>('modelValue');
</script>

<template>
  <TabsRoot v-model="model" :class="cn('flex flex-col gap-4', props.class)">
    <TabsList class="flex gap-1 border-b border-outline-variant">
      <TabsTrigger
        v-for="tab in tabs"
        :key="tab.value"
        :value="tab.value"
        class="-mb-px inline-flex items-center gap-2 whitespace-nowrap border-b-[3px] border-transparent px-4 py-2.5 text-sm font-medium text-on-surface-variant transition-colors hover:text-on-surface data-[state=active]:border-primary data-[state=active]:font-semibold data-[state=active]:text-primary outline-none focus-visible:ring-2 focus-visible:ring-ring"
      >
        <AppIcon v-if="tab.icon" :name="tab.icon" :size="18" />
        {{ tab.label }}
      </TabsTrigger>
    </TabsList>
    <TabsContent
      v-for="tab in tabs"
      :key="tab.value"
      :value="tab.value"
      class="text-sm text-on-surface outline-none"
    >
      <slot :name="`tab-${tab.value}`" />
    </TabsContent>
  </TabsRoot>
</template>

// apps/web-next/components/ui/tabs.tsx
'use client';

import { cn } from '@/lib/utils';
import { useRef, useState, type KeyboardEvent } from 'react';

export interface TabDef {
  value: string;
  label: string;
}

/**
 * MD3 primary tabs (port of the Nuxt variant's ui/Tabs.vue): active tab
 * colored primary with a 3dp bottom indicator and semibold label. Hand-rolled
 * tablist with arrow-key roving so no extra primitive dependency is needed
 * for a static code-sample switcher. Panel content per tab arrives as the
 * `panels` record (server-renderable nodes passed into this client island).
 */
export function Tabs({
  tabs,
  panels,
  className,
}: {
  tabs: TabDef[];
  panels: Record<string, React.ReactNode>;
  className?: string;
}) {
  const [value, setValue] = useState(tabs[0]!.value);
  const interacted = useRef(false);
  const listRef = useRef<HTMLDivElement>(null);

  const activeIndex = Math.max(
    0,
    tabs.findIndex((tab) => tab.value === value),
  );

  // Focus follows the selection only after a real user interaction — never
  // on first paint, which would steal focus from the page.
  function focusActive() {
    if (!interacted.current) return;
    listRef.current?.querySelectorAll<HTMLButtonElement>('[role="tab"]')[activeIndex]?.focus();
  }

  function select(next: string) {
    interacted.current = true;
    setValue(next);
    requestAnimationFrame(focusActive);
  }

  function onKeyDown(event: KeyboardEvent<HTMLDivElement>) {
    if (event.key !== 'ArrowRight' && event.key !== 'ArrowLeft') return;
    event.preventDefault();
    select(
      tabs[(activeIndex + (event.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length]!
        .value,
    );
  }

  return (
    <div className={cn('flex flex-col gap-4', className)}>
      <div
        ref={listRef}
        role="tablist"
        className="flex gap-1 border-b border-outline-variant"
        onKeyDown={onKeyDown}
      >
        {tabs.map((tab, index) => {
          const active = index === activeIndex;
          return (
            <button
              key={tab.value}
              type="button"
              role="tab"
              id={`tab-${tab.value}`}
              aria-selected={active}
              aria-controls={`tabpanel-${tab.value}`}
              tabIndex={active ? 0 : -1}
              className={cn(
                '-mb-px inline-flex items-center gap-2 whitespace-nowrap border-b-[3px] border-transparent px-4 py-2.5 text-sm font-medium text-on-surface-variant outline-none transition-colors hover:text-on-surface focus-visible:ring-2 focus-visible:ring-ring',
                active && 'border-primary font-semibold text-primary',
              )}
              onClick={() => select(tab.value)}
            >
              {tab.label}
            </button>
          );
        })}
      </div>
      {tabs.map((tab, index) => (
        <div
          key={tab.value}
          role="tabpanel"
          id={`tabpanel-${tab.value}`}
          aria-labelledby={`tab-${tab.value}`}
          hidden={index !== activeIndex}
          className="text-sm text-on-surface outline-none"
        >
          {index === activeIndex ? panels[tab.value] : null}
        </div>
      ))}
    </div>
  );
}
