// apps/web/app/components/shell/AppSidebar.vue
<script setup lang="ts">
import { useAuthStore } from '~/stores/auth';
import { useBranding } from '~/composables/useBranding';

const branding = useBranding();

const auth = useAuthStore();
const route = useRoute();
const { isExpanded, isMobileOpen, closeMobile } = useSidebar();

interface NavItem {
  label: string;
  to: string;
  icon: string; // Material Symbols name
  adminOnly?: boolean;
}

// Only existing routes — kept minimal per the starter kit's surface.
const items: NavItem[] = [
  { label: 'nav.dashboard', to: '/admin/dashboard', icon: 'grid_view' },
  { label: 'nav.users', to: '/admin/users', icon: 'group', adminOnly: true },
  // Shield glyph: access control, the meaning roles carry in this app.
  { label: 'nav.roles', to: '/admin/roles', icon: 'admin_panel_settings', adminOnly: true },
  { label: 'nav.settings', to: '/admin/settings', icon: 'settings', adminOnly: true },
  { label: 'nav.fieldsDemo', to: '/admin/demo/fields', icon: 'science' },
  { label: 'nav.componentsDemo', to: '/admin/demo/components', icon: 'widgets' },
];

// Auth roles are only known on the client (the access token lives in memory), so
// admin-only items must stay hidden until after mount. Rendering them during SSR
// — or on the client's first (hydration) pass — would make the server nav (guest
// view) and the hydrated client nav (authed view) diverge, which Vue reports as a
// hydration mismatch. `import.meta.client` is already true during hydration, so a
// post-mount flag is what keeps the first client render identical to the server's.
const mounted = ref(false);
onMounted(() => {
  mounted.value = true;
});

const visibleItems = computed(() =>
  items.filter((i) => !i.adminOnly || (mounted.value && auth.isAuthenticated && auth.isAdmin)),
);

function isActive(to: string) {
  return route.path === to || route.path.startsWith(to + '/');
}

// The icon-only rail is a desktop concept; the mobile drawer is always full.
const showFull = computed(() => isMobileOpen.value || isExpanded.value);
</script>

<template>
  <!-- Mobile scrim (MD3 modal drawer) -->
  <div v-if="isMobileOpen" class="fixed inset-0 z-40 bg-scrim lg:hidden" @click="closeMobile" />

  <!-- MD3 navigation drawer (256dp) / rail (80dp collapsed), no divider:
       separation comes from tonal surfaces, not a border. -->
  <aside
    :class="[
      'fixed inset-y-0 left-0 z-50 flex flex-col bg-sidebar transition-[width,transform] duration-300 ease-emphasized',
      'w-64',
      isExpanded ? 'lg:w-64' : 'lg:w-20',
      isMobileOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0',
    ]"
  >
    <!-- Brand -->
    <div :class="['flex h-16 items-center', showFull ? 'px-4' : 'justify-center px-0']">
      <NuxtLink
        to="/admin/dashboard"
        class="flex items-center gap-2.5 font-semibold"
        @click="closeMobile"
      >
        <BrandLogo class="h-10" />
        <span v-if="showFull" class="text-base tracking-tight text-foreground">{{
          branding.appName
        }}</span>
      </NuxtLink>
    </div>

    <!-- Nav: active item is a tonal container with 12dp corners and a 4dp
         primary bar on the leading edge. Labeled because the page has a
         second nav landmark (the breadcrumb). -->
    <nav :aria-label="$t('nav.menu')" class="flex-1 overflow-y-auto px-3 py-2">
      <p
        :class="[
          'mb-2 px-4 text-xs font-medium text-muted-foreground',
          showFull ? '' : 'text-center',
        ]"
      >
        {{ showFull ? $t('nav.menu') : '•••' }}
      </p>
      <ul class="space-y-1">
        <li v-for="item in visibleItems" :key="item.to">
          <!-- Icon-only rail: the label moves into a right-side tooltip;
               disabled when the sidebar is expanded (the label is visible). -->
          <Tooltip :text="$t(item.label)" side="right" :disabled="showFull">
            <NuxtLink
              :to="item.to"
              :class="[
                'group relative flex items-center rounded-lg text-sm font-medium transition-colors',
                showFull ? 'gap-3 px-4 py-3' : 'justify-center px-0 py-3',
                isActive(item.to)
                  ? 'bg-sidebar-accent font-semibold text-sidebar-accent-foreground'
                  : 'text-muted-foreground hover:bg-on-surface/8 hover:text-foreground',
              ]"
              @click="closeMobile"
            >
              <!-- Active indicator: 4dp primary bar pinned to the leading edge. -->
              <span
                v-if="isActive(item.to)"
                class="absolute left-0 top-1/2 h-5 w-1 -translate-y-1/2 rounded-full bg-primary"
              />
              <MaterialSymbol :name="item.icon" :size="22" class="shrink-0" />
              <span v-if="showFull">{{ $t(item.label) }}</span>
            </NuxtLink>
          </Tooltip>
        </li>
      </ul>
    </nav>

    <!-- Footer — user dropdown (same menu as the top-right header) -->
    <div :class="['border-t border-sidebar-border', showFull ? 'p-3' : 'flex justify-center p-2']">
      <UserMenu variant="full" placement="up" :show-details="showFull" />
    </div>
  </aside>
</template>

// apps/web-next/components/shell/app-sidebar.tsx
'use client';

import { BrandLogo } from '@/components/common/brand-logo';
import { UserMenu } from '@/components/shell/user-menu';
import { useBranding } from '@/lib/branding';
import { closeMobile, getSidebarState, subscribeSidebar } from '@/lib/use-sidebar';
import { CircleUserRound, LayoutDashboard, Settings, ShieldCheck, Users } from 'lucide-react';
import { useTranslations } from 'next-intl';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useSyncExternalStore } from 'react';

/**
 * MD3 navigation drawer (256dp) / rail (80dp collapsed) — the port of the
 * Nuxt variant's AppSidebar. Nav lists only routes that exist in this
 * variant; roles/settings join with their stages. No divider: separation
 * comes from tonal surfaces.
 */
export function AppSidebar() {
  const t = useTranslations();
  const pathname = usePathname();
  const { isExpanded, isMobileOpen } = useSyncExternalStore(
    subscribeSidebar,
    getSidebarState,
    getSidebarState,
  );
  const branding = useBranding();

  // The icon-only rail is a desktop concept; the mobile drawer is always full.
  const showFull = isMobileOpen || isExpanded;

  const items = [
    { label: t('nav.dashboard'), href: '/admin/dashboard', icon: LayoutDashboard },
    { label: t('nav.users'), href: '/admin/users', icon: Users },
    // Shield glyph: access control, the meaning roles carry in this app.
    { label: t('nav.roles'), href: '/admin/roles', icon: ShieldCheck },
    { label: t('nav.profile'), href: '/admin/profile', icon: CircleUserRound },
    { label: t('nav.settings'), href: '/admin/settings', icon: Settings },
  ];

  function isActive(href: string) {
    return pathname === href || pathname.startsWith(href + '/');
  }

  return (
    <>
      {/* Mobile scrim (MD3 modal drawer) */}
      {isMobileOpen && (
        <div
          className="fixed inset-0 z-40 bg-scrim lg:hidden"
          onClick={closeMobile}
          aria-hidden="true"
        />
      )}

      <aside
        className={`fixed inset-y-0 left-0 z-50 flex w-64 flex-col bg-sidebar transition-[width,transform] duration-300 ease-emphasized ${
          isExpanded ? 'lg:w-64' : 'lg:w-20'
        } ${isMobileOpen ? 'translate-x-0' : '-translate-x-full lg:translate-x-0'}`}
      >
        {/* Brand */}
        <div className={`flex h-16 items-center ${showFull ? 'px-4' : 'justify-center px-0'}`}>
          <Link
            href="/admin/dashboard"
            className="flex items-center gap-2.5 font-semibold"
            onClick={closeMobile}
          >
            <BrandLogo className="h-10" />
            {showFull && (
              <span className="text-base tracking-tight text-foreground">{branding.appName}</span>
            )}
          </Link>
        </div>

        {/* Nav: active item is a tonal container with 12dp corners and a 4dp
             primary bar on the leading edge. */}
        <nav aria-label={t('nav.menu')} className="flex-1 overflow-y-auto px-3 py-2">
          <p
            className={`mb-2 px-4 text-xs font-medium text-muted-foreground ${showFull ? '' : 'text-center'}`}
          >
            {showFull ? t('nav.menu') : '•••'}
          </p>
          <ul className="space-y-1">
            {items.map((item) => {
              const Icon = item.icon;
              return (
                <li key={item.href}>
                  <Link
                    href={item.href}
                    title={showFull ? undefined : item.label}
                    className={`group relative flex items-center rounded-lg text-sm font-medium transition-colors ${
                      showFull ? 'gap-3 px-4 py-3' : 'justify-center px-0 py-3'
                    } ${
                      isActive(item.href)
                        ? 'bg-sidebar-accent font-semibold text-sidebar-accent-foreground'
                        : 'text-muted-foreground hover:bg-on-surface/8 hover:text-foreground'
                    }`}
                    onClick={closeMobile}
                  >
                    {isActive(item.href) && (
                      <span className="absolute left-0 top-1/2 h-5 w-1 -translate-y-1/2 rounded-full bg-primary" />
                    )}
                    <Icon size={22} className="shrink-0" aria-hidden="true" />
                    {showFull && <span>{item.label}</span>}
                  </Link>
                </li>
              );
            })}
          </ul>
        </nav>

        {/* Footer — session card with sign-out */}
        <div
          className={`border-t border-sidebar-border ${showFull ? 'p-3' : 'flex justify-center p-2'}`}
        >
          <UserMenu showDetails={showFull} />
        </div>
      </aside>
    </>
  );
}
