// apps/web/app/pages/admin/settings.vue
<script setup lang="ts">
// Explicit barrel import — features/ is NOT auto-imported (SPEC boundary rule).
import { BrandingTab } from '~/features/settings';
import { useBranding } from '~/composables/useBranding';

definePageMeta({ layout: 'admin', middleware: ['auth', 'admin'] });
const { t } = useI18n();
const branding = useBranding();
useHead({ title: () => `Settings · ${branding.value.appName}` });

// Tabs from day one — future groups (general, mail, …) slot in without
// restructuring the page.
const tab = ref('branding');
const tabs = computed(() => [
  { value: 'branding', label: t('settings.tabs.branding'), icon: 'palette' },
]);
</script>

<template>
  <div class="space-y-6">
    <PageHeading
      :title="$t('settings.title')"
      :breadcrumbs="[
        { label: $t('nav.dashboard'), to: '/admin/dashboard' },
        { label: $t('settings.title') },
      ]"
    />

    <Tabs v-model="tab" :tabs="tabs">
      <template #tab-branding>
        <BrandingTab />
      </template>
    </Tabs>
  </div>
</template>

// apps/web-next/app/admin/settings/page.tsx
'use client';

import { PageHeading } from '@/components/blocks/page-heading';
import { Tabs } from '@/components/ui/tabs';
import { useTranslations } from 'next-intl';
import { BrandingTab } from '@/features/settings';

// Tabs from day one — future groups (general, mail, …) slot in without
// restructuring the page.
export default function SettingsPage() {
  const t = useTranslations();
  return (
    <div className="space-y-6">
      <PageHeading
        title={t('settings.title')}
        breadcrumbs={[
          { label: t('nav.dashboard'), href: '/admin/dashboard' },
          { label: t('settings.title') },
        ]}
      />

      <Tabs
        tabs={[{ value: 'branding', label: t('settings.tabs.branding') }]}
        panels={{
          branding: <BrandingTab />,
        }}
      />
    </div>
  );
}
