// apps/web-next/components/ui/checkbox.tsx
'use client';

import { cn } from '@/lib/utils';
import { Check } from 'lucide-react';
import { useId, type InputHTMLAttributes, type Ref } from 'react';

/**
 * MD3 checkbox: rounded 2dp box, primary fill when checked. Plain input +
 * visual overlay so native form semantics and screen readers stay intact.
 */
export function Checkbox({
  className,
  ref,
  ...props
}: InputHTMLAttributes<HTMLInputElement> & { ref?: Ref<HTMLInputElement> }) {
  const fallbackId = useId();
  return (
    <span className={cn('relative inline-flex h-5 w-5 shrink-0', className)}>
      <input
        type="checkbox"
        id={props.id ?? fallbackId}
        ref={ref}
        className="peer absolute inset-0 h-full w-full cursor-pointer appearance-none"
        {...props}
      />
      <span
        className="pointer-events-none flex h-5 w-5 items-center justify-center rounded-[2px] border border-outline bg-transparent transition-colors peer-checked:border-primary peer-checked:bg-primary peer-focus-visible:ring-2 peer-focus-visible:ring-ring peer-focus-visible:ring-offset-2 peer-focus-visible:ring-offset-background"
        aria-hidden="true"
      >
        {props.checked && (
          <Check size={14} className="text-primary-foreground" aria-hidden="true" />
        )}
      </span>
    </span>
  );
}

// apps/web/app/components/ui/Checkbox.vue
<script setup lang="ts">
import type { CheckboxRootEmits, CheckboxRootProps } from 'reka-ui';
import type { HTMLAttributes } from 'vue';
import { CheckboxIndicator, CheckboxRoot, useForwardPropsEmits } from 'reka-ui';
import { cn } from '~/lib/utils';

// MD3 checkbox: 18dp box, 2dp rounded corners, 2dp outline unchecked; checked
// fills primary with an on-primary check glyph. Vue 3.5's reactive props
// rest-spread omits `class` without an extra dependency.
const { class: _c, ...delegatedProps } = defineProps<
  CheckboxRootProps & { class?: HTMLAttributes['class'] }
>();
const emits = defineEmits<CheckboxRootEmits>();

const forwarded = useForwardPropsEmits(delegatedProps, emits);
</script>

<template>
  <CheckboxRoot
    v-slot="slotProps"
    data-slot="checkbox"
    v-bind="forwarded"
    :class="
      cn(
        'peer size-[18px] shrink-0 rounded-[2px] border-2 border-outline outline-none transition-colors focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive data-[state=checked]:border-primary data-[state=checked]:bg-primary data-[state=checked]:text-primary-foreground',
        _c,
      )
    "
  >
    <CheckboxIndicator
      data-slot="checkbox-indicator"
      class="grid place-content-center text-current transition-none"
    >
      <slot v-bind="slotProps">
        <MaterialSymbol name="check" :size="14" />
      </slot>
    </CheckboxIndicator>
  </CheckboxRoot>
</template>
