// apps/web-next/components/ui/modal.tsx
'use client';

import { cn } from '@/lib/utils';
import { X } from 'lucide-react';
import { useEffect, type ReactNode } from 'react';

/**
 * MD3 dialog (port of the Nuxt variant's Modal surface): scrim fades, panel
 * settles from a hair of scale (keyframes in globals.css), closable with
 * Escape and the scrim. Surface-container elevation, never shadows.
 */
export function Modal({
  open,
  onOpenChange,
  title,
  description,
  children,
  className,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  title: string;
  description?: string;
  children: ReactNode;
  className?: string;
}) {
  useEffect(() => {
    if (!open) return;
    const onKey = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onOpenChange(false);
    };
    document.addEventListener('keydown', onKey);
    return () => document.removeEventListener('keydown', onKey);
  }, [open, onOpenChange]);

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[60] grid place-items-center p-4">
      <div
        className="absolute inset-0 animate-[fade-in_150ms_ease-out] bg-scrim"
        onClick={() => onOpenChange(false)}
        aria-hidden="true"
      />
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="modal-title"
        className={cn(
          'relative w-full max-w-md animate-[dialog-in_200ms_var(--ease-emphasized-decelerate)] rounded-2xl bg-surface-container-low p-6 shadow-theme-lg',
          className,
        )}
      >
        <div className="mb-4 flex items-start justify-between gap-4">
          <div>
            <h2 id="modal-title" className="text-lg font-semibold text-on-surface">
              {title}
            </h2>
            {description && <p className="mt-1 text-sm text-on-surface-variant">{description}</p>}
          </div>
          <button
            type="button"
            className="touch-target relative flex h-9 w-9 shrink-0 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-on-surface-variant/10 hover:text-foreground"
            aria-label="Close"
            onClick={() => onOpenChange(false)}
          >
            <X size={18} aria-hidden="true" />
          </button>
        </div>
        {children}
      </div>
    </div>
  );
}

// apps/web/app/components/ui/Modal.vue
<script setup lang="ts">
import {
  DialogRoot,
  DialogPortal,
  DialogOverlay,
  DialogContent,
  DialogTitle,
  DialogDescription,
  DialogClose,
} from 'reka-ui';

/** Reusable modal dialog (reka-ui). Control with `v-model:open`. */
const open = defineModel<boolean>('open', { default: false });
defineProps<{ title?: string; description?: string }>();
</script>

<template>
  <DialogRoot v-model:open="open">
    <DialogPortal>
      <!-- MD3 scrim: plain 32% black, no blur. -->
      <DialogOverlay class="fixed inset-0 z-50 bg-scrim" />
      <!-- MD3 basic dialog: 28dp corners, surface-container-high, elevation 3,
           no border. Scrolls vertically when content overflows (capped at
           90vh); overscroll-contain stops wheel/touch chaining past the
           dialog edges. -->
      <DialogContent
        class="fixed left-1/2 top-1/2 z-50 max-h-[90vh] w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 overflow-y-auto overscroll-contain rounded-2xl bg-surface-container-high p-6 shadow-theme-lg focus:outline-none"
      >
        <div class="mb-5 flex items-start justify-between gap-4">
          <div class="space-y-1">
            <DialogTitle v-if="title" class="text-lg font-semibold text-foreground">
              {{ title }}
            </DialogTitle>
            <DialogDescription v-if="description" class="text-sm text-muted-foreground">
              {{ description }}
            </DialogDescription>
          </div>
          <DialogClose
            class="touch-target relative rounded-full p-2 text-muted-foreground transition-colors hover:bg-on-surface-variant/10 hover:text-foreground"
            aria-label="Close"
          >
            <MaterialSymbol name="close" :size="20" />
          </DialogClose>
        </div>
        <slot />
      </DialogContent>
    </DialogPortal>
  </DialogRoot>
</template>
