// apps/web/app/components/common/fields/PasswordField.vue
<script setup lang="ts">
import { useField } from 'vee-validate';
import { toRef, ref } from 'vue';
import { cn } from '~/lib/utils';

const props = defineProps<{
  name: string;
  label?: string;
  placeholder?: string;
  required?: boolean;
  /** Lucide icon name for a leading glyph (e.g. 'lock'). */
  prefixIcon?: string;
  /** MD3 supporting text below the field; the error replaces it when present. */
  hint?: string;
  /** Passed through for password managers ('current-password' | 'new-password'). */
  autocomplete?: string;
}>();

const { t } = useI18n();
const { value, errorMessage } = useField<string>(toRef(props, 'name'));
const show = ref(false);
</script>

<template>
  <Fieldset :name="name" :label="label" :required="required" :error="errorMessage" :hint="hint">
    <template #default="{ describedBy, invalid }">
      <div class="relative">
        <Input
          :id="name"
          v-model="value"
          :type="show ? 'text' : 'password'"
          :placeholder="placeholder"
          :prefix-icon="prefixIcon"
          :autocomplete="autocomplete"
          :aria-describedby="describedBy"
          :aria-invalid="invalid"
          :class="
            cn(
              'pr-12',
              errorMessage && 'border-destructive focus:border-destructive focus:ring-destructive',
            )
          "
        />
        <button
          type="button"
          class="touch-target absolute right-2 top-1/2 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-on-surface-variant/10 hover:text-foreground [--touch-slop:-6px]"
          :aria-label="show ? t('auth.hidePassword') : t('auth.showPassword')"
          :aria-pressed="show"
          @click="show = !show"
        >
          <AppIcon :name="show ? 'visibility' : 'visibility_off'" :size="18" />
        </button>
      </div>
    </template>
  </Fieldset>
</template>

// apps/web-next/components/common/password-field.tsx
'use client';

import { Field } from '@/components/common/field';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import { Eye, EyeOff, type LucideIcon } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { useState } from 'react';
import { useController, type Control, type FieldValues, type Path } from 'react-hook-form';

/**
 * Password input with the show/hide eye, RHF-integrated (port of the Nuxt
 * variant's PasswordField). `autocomplete` is passed through for password
 * managers ('current-password' | 'new-password').
 */
export interface PasswordFieldProps<T extends FieldValues> {
  name: Path<T>;
  control: Control<T>;
  label?: string;
  placeholder?: string;
  required?: boolean;
  prefixIcon?: LucideIcon;
  hint?: string;
  autocomplete?: string;
}

export function PasswordField<T extends FieldValues>({
  name,
  control,
  label,
  placeholder,
  required,
  prefixIcon,
  hint,
  autocomplete,
}: PasswordFieldProps<T>) {
  const t = useTranslations('auth');
  const { field, fieldState } = useController({ name, control });
  const [show, setShow] = useState(false);
  const error = fieldState.error?.message;

  return (
    <Field label={label} error={error} hint={hint} required={required}>
      {({ id, describedBy, invalid }) => (
        <div className="relative">
          <Input
            id={id}
            ref={field.ref}
            name={field.name}
            value={field.value ?? ''}
            onChange={field.onChange}
            onBlur={field.onBlur}
            type={show ? 'text' : 'password'}
            placeholder={placeholder}
            prefixIcon={prefixIcon}
            autoComplete={autocomplete}
            aria-describedby={describedBy}
            aria-invalid={invalid}
            className={cn(
              'pr-12',
              error && 'border-destructive focus:border-destructive focus:ring-destructive',
            )}
          />
          <button
            type="button"
            className="touch-target absolute right-2 top-1/2 flex h-8 w-8 -translate-y-1/2 items-center justify-center rounded-full text-muted-foreground transition-colors hover:bg-on-surface-variant/10 hover:text-foreground [--touch-slop:-6px]"
            aria-label={show ? t('hidePassword') : t('showPassword')}
            aria-pressed={show}
            onClick={() => setShow((value) => !value)}
          >
            {show ? <EyeOff size={18} aria-hidden="true" /> : <Eye size={18} aria-hidden="true" />}
          </button>
        </div>
      )}
    </Field>
  );
}
