// apps/web-next/components/common/text-field.tsx
'use client';

import { Field } from '@/components/common/field';
import { Input } from '@/components/ui/input';
import { cn } from '@/lib/utils';
import type { LucideIcon } from 'lucide-react';
import { useController, type Control, type FieldValues, type Path } from 'react-hook-form';

/**
 * Label + input + error, integrated with React Hook Form via useController —
 * the port of the Nuxt variant's VeeValidate TextField. Validation lives in
 * the form's zod schema; this component only renders the result.
 */
export interface TextFieldProps<T extends FieldValues> {
  name: Path<T>;
  control: Control<T>;
  label?: string;
  type?: string;
  placeholder?: string;
  required?: boolean;
  prefixIcon?: LucideIcon;
  hint?: string;
  inputmode?: 'text' | 'numeric' | 'tel' | 'email' | 'url';
  maxLength?: number;
  disabled?: boolean;
}

export function TextField<T extends FieldValues>({
  name,
  control,
  label,
  type = 'text',
  placeholder,
  required,
  prefixIcon,
  hint,
  inputmode,
  maxLength,
  disabled,
}: TextFieldProps<T>) {
  const { field, fieldState } = useController({ name, control });
  const error = fieldState.error?.message;

  return (
    <Field label={label} error={error} hint={hint} required={required}>
      {({ id, describedBy, invalid }) => (
        <Input
          id={id}
          ref={field.ref}
          name={field.name}
          value={field.value ?? ''}
          onChange={field.onChange}
          onBlur={field.onBlur}
          type={type}
          placeholder={placeholder}
          prefixIcon={prefixIcon}
          inputMode={inputmode}
          maxLength={maxLength}
          disabled={disabled}
          aria-describedby={describedBy}
          aria-invalid={invalid}
          className={cn(
            error && 'border-destructive focus:border-destructive focus:ring-destructive',
          )}
        />
      )}
    </Field>
  );
}

// apps/web/app/components/common/fields/TextField.vue
<script setup lang="ts">
import { useField } from 'vee-validate';
import { toRef } from 'vue';
import { cn } from '~/lib/utils';

/**
 * SPEC DRY #2 (FE) — label + input + error, integrated via VeeValidate `useField`.
 * Must be used inside a VeeValidate form (`useForm` / `<Form>`).
 */
const props = defineProps<{
  name: string;
  label?: string;
  type?: string;
  placeholder?: string;
  required?: boolean;
  /** Lucide icon name for a leading glyph (e.g. 'lock'). */
  prefixIcon?: string;
  /** MD3 supporting text below the field; the error replaces it when present. */
  hint?: string;
  /** HTML inputmode hint (e.g. 'numeric' for OTP entry). */
  inputmode?: 'text' | 'numeric' | 'tel' | 'email' | 'url';
  /** Hard character cap (e.g. OTP codes). */
  maxlength?: number;
  disabled?: boolean;
}>();

const { value, errorMessage } = useField<string>(toRef(props, 'name'));
</script>

<template>
  <Fieldset :name="name" :label="label" :required="required" :error="errorMessage" :hint="hint">
    <template v-if="$slots.label" #label>
      <slot name="label" />
    </template>
    <template #default="{ describedBy, invalid }">
      <Input
        :id="name"
        v-model="value"
        :type="type ?? 'text'"
        :placeholder="placeholder"
        :prefix-icon="prefixIcon"
        :inputmode="inputmode"
        :maxlength="maxlength"
        :disabled="disabled"
        :aria-describedby="describedBy"
        :aria-invalid="invalid"
        :class="
          cn(errorMessage && 'border-destructive focus:border-destructive focus:ring-destructive')
        "
      />
    </template>
  </Fieldset>
</template>
