// apps/web/app/pages/admin/users/index.vue
<script setup lang="ts">
// Explicit barrel import — features/ is NOT auto-imported (SPEC boundary rule).
import { UserTable } from '~/features/user';
import { APP_NAME } from '~/lib/constants';

definePageMeta({ layout: 'admin', middleware: ['auth', 'admin'] });
useHead({ title: `Users · ${APP_NAME}` });
</script>

<template>
  <div class="space-y-6">
    <PageHeading
      :title="$t('users.title')"
      :breadcrumbs="[
        { label: $t('nav.dashboard'), to: '/admin/dashboard' },
        { label: $t('users.title') },
      ]"
    />

    <UserTable />
  </div>
</template>

// apps/web-next/app/admin/users/page.tsx
'use client';

import { PageHeading } from '@/components/blocks/page-heading';
import { usePageTitle } from '@/lib/use-page-title';
import { useTranslations } from 'next-intl';
import { UsersTable } from '@/features/user';

// Thin page: the feature slice owns the table (explicit barrel import —
// features/ is not auto-imported).
export default function UsersPage() {
  const t = useTranslations();
  usePageTitle(t('users.title'));
  return (
    <div className="space-y-6">
      <PageHeading
        title={t('users.title')}
        breadcrumbs={[
          { label: t('nav.dashboard'), href: '/admin/dashboard' },
          { label: t('users.title') },
        ]}
      />
      <UsersTable />
    </div>
  );
}
