// apps/web-next/features/profile/components/change-password-card.tsx
'use client';

import { PasswordField } from '@/components/common/password-field';
import { Button } from '@/components/ui/button';
import { applyApiFieldErrors } from '@/lib/api-errors';
import { useConfirm } from '@/lib/use-confirm';
import { zodResolver } from '@hookform/resolvers/zod';
import { useTranslations } from 'next-intl';
import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { z } from 'zod';
import { useChangePassword } from '../hooks';

const schema = z
  .object({
    currentPassword: z.string().min(1, 'Enter your current password'),
    newPassword: z.string().min(8, 'New password must be at least 8 characters'),
    confirmPassword: z.string(),
  })
  .refine((v) => v.newPassword === v.confirmPassword, {
    message: 'Passwords do not match',
    path: ['confirmPassword'],
  });

/** Change-password card — password-confirmed via the destructive confirm. */
export function ChangePasswordCard() {
  const t = useTranslations('profile.changePassword');
  const change = useChangePassword();
  const { confirm } = useConfirm();
  const [confirming, setConfirming] = useState(false);
  const pending = confirming || change.isPending;

  const { control, handleSubmit, reset, setError } = useForm<z.infer<typeof schema>>({
    resolver: zodResolver(schema),
    defaultValues: { currentPassword: '', newPassword: '', confirmPassword: '' },
  });

  const onSubmit = handleSubmit(async (values) => {
    if (pending) return;
    setConfirming(true);
    try {
      const ok = await confirm({
        title: t('confirmTitle'),
        description: t('confirmDescription'),
        confirmText: t('update'),
        destructive: true,
      });
      if (!ok) return;
      await change.mutateAsync({
        currentPassword: values.currentPassword,
        newPassword: values.newPassword,
      });
      reset();
    } catch (err) {
      applyApiFieldErrors(
        err,
        (errors) => {
          for (const [field, message] of Object.entries(errors))
            setError(field as never, { message });
        },
        ['currentPassword', 'newPassword', 'confirmPassword'],
      );
    } finally {
      setConfirming(false);
    }
  });

  return (
    <div className="rounded-lg border border-outline-variant bg-card p-5 sm:p-6">
      <div className="mb-1">
        <h3 className="text-base font-semibold text-foreground">{t('title')}</h3>
        <p className="mt-1 text-sm text-muted-foreground">{t('subtitle')}</p>
      </div>

      <form className="mt-5 space-y-5" onSubmit={onSubmit}>
        <div className="max-w-md">
          <PasswordField
            name="currentPassword"
            control={control}
            label={t('currentPassword')}
            placeholder="••••••••"
            autocomplete="current-password"
          />
        </div>
        <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
          <PasswordField
            name="newPassword"
            control={control}
            label={t('newPassword')}
            placeholder="••••••••"
            autocomplete="new-password"
          />
          <PasswordField
            name="confirmPassword"
            control={control}
            label={t('confirmPassword')}
            placeholder="••••••••"
            autocomplete="new-password"
          />
        </div>

        <div className="flex justify-end">
          <Button type="submit" disabled={pending}>
            {pending ? t('updating') : t('update')}
          </Button>
        </div>
      </form>
    </div>
  );
}

// apps/web/app/features/profile/components/ChangePasswordCard.vue
<script setup lang="ts">
import { applyApiFieldErrors } from '~/lib/api-errors';
import { ref, computed } from 'vue';
import { useForm } from 'vee-validate';
import { toTypedSchema } from '@vee-validate/zod';
import { z } from 'zod';
import { useChangePassword } from '../composables/useProfile';

const change = useChangePassword();
const { t } = useI18n();
const { confirm } = useConfirm();
const confirming = ref(false);
const pending = computed(() => confirming.value || change.isPending.value);

const schema = toTypedSchema(
  z
    .object({
      currentPassword: z.string().min(1, 'Enter your current password'),
      newPassword: z.string().min(8, 'New password must be at least 8 characters'),
      confirmPassword: z.string(),
    })
    .refine((v) => v.newPassword === v.confirmPassword, {
      message: 'Passwords do not match',
      path: ['confirmPassword'],
    }),
);

const { handleSubmit, resetForm, setErrors } = useForm({ validationSchema: schema });

const onSubmit = handleSubmit(async (values) => {
  if (pending.value) return;
  confirming.value = true;
  try {
    const ok = await confirm({
      title: t('profile.changePassword.confirmTitle'),
      description: t('profile.changePassword.confirmDescription'),
      confirmText: t('profile.changePassword.update'),
      destructive: true,
    });
    if (!ok) return;
    await change.mutateAsync({
      currentPassword: values.currentPassword,
      newPassword: values.newPassword,
    });
    resetForm();
  } catch (err) {
    applyApiFieldErrors(err, setErrors, ['currentPassword', 'newPassword', 'confirmPassword']);
  } finally {
    confirming.value = false;
  }
});
</script>

<template>
  <div class="rounded-lg border border-outline-variant bg-card p-5 sm:p-6">
    <div class="mb-1">
      <h3 class="text-base font-semibold text-foreground">
        {{ $t('profile.changePassword.title') }}
      </h3>
      <p class="mt-1 text-sm text-muted-foreground">{{ $t('profile.changePassword.subtitle') }}</p>
    </div>

    <form class="mt-5 space-y-5" @submit="onSubmit">
      <div class="max-w-md">
        <PasswordField
          name="currentPassword"
          :label="$t('profile.changePassword.currentPassword')"
          placeholder="••••••••"
          autocomplete="current-password"
        />
      </div>
      <div class="grid grid-cols-1 gap-5 sm:grid-cols-2">
        <PasswordField
          name="newPassword"
          :label="$t('profile.changePassword.newPassword')"
          placeholder="••••••••"
          autocomplete="new-password"
        />
        <PasswordField
          name="confirmPassword"
          :label="$t('profile.changePassword.confirmPassword')"
          placeholder="••••••••"
          autocomplete="new-password"
        />
      </div>

      <div class="flex justify-end">
        <Button type="submit" :disabled="pending">
          {{
            pending ? $t('profile.changePassword.updating') : $t('profile.changePassword.update')
          }}
        </Button>
      </div>
    </form>
  </div>
</template>
