// apps/web-next/features/profile/components/profile-header-card.tsx
'use client';

import { Badge } from '@/components/ui/badge';
import { Field } from '@/components/common/field';
import { apiFieldErrors } from '@/lib/api-errors';
import { roleLabel } from '@/lib/roles';
import { uploadFile } from '@/lib/upload';
import type { User } from '@nuxion/shared-types';
import { Camera, LoaderCircle, Mail, Shield } from 'lucide-react';
import { useTranslations } from 'next-intl';
import { useRef, useState, type ChangeEvent } from 'react';
import { toast } from 'sonner';
import { useUpdateProfile } from '../hooks';

/**
 * Profile header: avatar with an upload affordance (pick → POST /files →
 * PATCH /users/me with the URL), name, role + email, role badges. Port of the
 * Nuxt variant's ProfileHeaderCard.
 */
export function ProfileHeaderCard({ user }: { user: User }) {
  const t = useTranslations();
  const update = useUpdateProfile();
  const fileInput = useRef<HTMLInputElement>(null);
  const [uploading, setUploading] = useState(false);
  const [avatarError, setAvatarError] = useState<string>();

  const initials = (() => {
    const name = user.name?.trim();
    if (!name) return 'U';
    return name
      .split(/\s+/)
      .slice(0, 2)
      .map((p) => p[0]?.toUpperCase())
      .join('');
  })();
  const primaryRole = user.roles?.[0] ?? 'USER';
  const MAX_MB = 5;

  function onPick(event: ChangeEvent<HTMLInputElement>) {
    const input = event.target;
    const file = input.files?.[0];
    input.value = '';
    if (!file) return;
    setAvatarError(undefined);
    if (!file.type.startsWith('image/')) {
      setAvatarError(t('profile.avatar.notImage'));
      toast.error(t('profile.avatar.notImage'));
      return;
    }
    if (file.size > MAX_MB * 1024 * 1024) {
      setAvatarError(t('profile.avatar.tooLarge', { mb: MAX_MB }));
      toast.error(t('profile.avatar.tooLarge', { mb: MAX_MB }));
      return;
    }

    setUploading(true);
    void (async () => {
      try {
        const { url } = await uploadFile(file, 'avatars');
        await update.mutateAsync({ avatarUrl: url }).catch((err) => {
          setAvatarError(apiFieldErrors(err).avatarUrl);
        });
      } catch (err) {
        const message =
          apiFieldErrors(err).file || (err as Error)?.message || t('profile.avatar.uploadFailed');
        setAvatarError(message);
        toast.error(message);
      } finally {
        setUploading(false);
        if (fileInput.current) fileInput.current.value = '';
      }
    })();
  }

  return (
    <div className="rounded-lg border border-outline-variant bg-card p-5 sm:p-6">
      <div className="flex flex-col items-center gap-5 sm:flex-row sm:items-center sm:gap-6">
        <Field error={avatarError} className="shrink-0 sm:max-w-44">
          {({ id, describedBy, invalid }) => (
            <div className="relative h-20 w-20">
              {user.avatarUrl ? (
                // eslint-disable-next-line @next/next/no-img-element -- API-served avatar URL
                <img
                  src={user.avatarUrl}
                  alt={user.name}
                  className="h-20 w-20 rounded-full object-cover"
                />
              ) : (
                <span className="flex h-20 w-20 items-center justify-center rounded-full bg-primary-container text-2xl font-semibold text-on-primary-container">
                  {initials}
                </span>
              )}

              {/* MD3 small FAB (primary-container) */}
              <button
                type="button"
                className="state-layer touch-target absolute -bottom-1 -right-1 flex h-8 w-8 items-center justify-center rounded-lg border-2 border-card bg-primary-container text-on-primary-container shadow disabled:opacity-60 [--touch-slop:-6px]"
                disabled={uploading}
                aria-label={uploading ? t('common.working') : t('profile.avatar.change')}
                aria-describedby={describedBy}
                onClick={() => fileInput.current?.click()}
              >
                {uploading ? (
                  <LoaderCircle size={14} className="animate-spin" aria-hidden="true" />
                ) : (
                  <Camera size={14} aria-hidden="true" />
                )}
              </button>
              <input
                id={id}
                ref={fileInput}
                type="file"
                accept="image/*"
                className="hidden"
                disabled={uploading}
                aria-label={t('profile.avatar.change')}
                aria-describedby={describedBy}
                aria-invalid={invalid}
                onChange={onPick}
              />
            </div>
          )}
        </Field>

        <div className="flex-1 text-center sm:text-left">
          <h2 className="text-lg font-semibold text-foreground">{user.name}</h2>
          <div className="mt-2 flex flex-wrap items-center justify-center gap-x-4 gap-y-1.5 text-sm text-muted-foreground sm:justify-start">
            <span className="inline-flex items-center gap-1.5">
              <Shield size={18} aria-hidden="true" />
              {roleLabel(primaryRole, (key) => t(key))}
            </span>
            <span className="inline-flex items-center gap-1.5">
              <Mail size={18} aria-hidden="true" />
              {user.email}
            </span>
          </div>
        </div>

        <div className="flex flex-wrap justify-center gap-2 sm:justify-end">
          {user.roles.map((role) => (
            <Badge key={role} variant="muted">
              {roleLabel(role, (key) => t(key))}
            </Badge>
          ))}
        </div>
      </div>
    </div>
  );
}

// apps/web/app/features/profile/components/ProfileHeaderCard.vue
<script setup lang="ts">
import { apiFieldErrors } from '~/lib/api-errors';
import { computed, ref } from 'vue';
import { toast } from 'vue-sonner';
import type { User } from '@nuxion/shared-types';
import { roleLabel } from '~/lib/roles';
import { useUpload } from '~/composables/useUpload';
import { useUpdateProfile } from '../composables/useProfile';

const { t } = useI18n();

const props = defineProps<{ user: User }>();

const initials = computed(() => {
  const name = props.user.name?.trim();
  if (!name) return 'U';
  return name
    .split(/\s+/)
    .slice(0, 2)
    .map((p) => p[0]?.toUpperCase())
    .join('');
});

const primaryRole = computed(() => props.user.roles?.[0] ?? 'USER');

// ── Avatar upload: pick → upload to /files → PATCH /users/me with the URL ──────
const { uploadFile } = useUpload();
const update = useUpdateProfile();
const fileInput = ref<HTMLInputElement | null>(null);
const uploading = ref(false);
const avatarError = ref<string>();

const MAX_MB = 5;

async function onPick(e: Event) {
  const input = e.target as HTMLInputElement;
  const file = input.files?.[0];
  input.value = '';
  if (!file) return;
  avatarError.value = undefined;
  if (!file.type.startsWith('image/')) {
    avatarError.value = t('profile.avatar.notImage');
    toast.error(avatarError.value);
    return;
  }
  if (file.size > MAX_MB * 1024 * 1024) {
    avatarError.value = t('profile.avatar.tooLarge', { mb: MAX_MB });
    toast.error(avatarError.value);
    return;
  }

  uploading.value = true;
  try {
    const { url } = await uploadFile(file, 'avatars');
    await update.mutateAsync({ avatarUrl: url }).catch((err) => {
      avatarError.value = apiFieldErrors(err).avatarUrl;
    });
  } catch (err) {
    avatarError.value =
      apiFieldErrors(err).file || (err as Error)?.message || t('profile.avatar.uploadFailed');
    toast.error(avatarError.value);
  } finally {
    uploading.value = false;
    if (fileInput.value) fileInput.value.value = '';
  }
}
</script>

<template>
  <div class="rounded-lg border border-outline-variant bg-card p-5 sm:p-6">
    <div class="flex flex-col items-center gap-5 sm:flex-row sm:items-center sm:gap-6">
      <!-- Avatar with upload affordance -->
      <Fieldset name="profile-avatar" :error="avatarError" class="shrink-0 sm:max-w-44">
        <template #default="{ id, describedBy, invalid }">
          <div class="relative h-20 w-20">
            <img
              v-if="user.avatarUrl"
              :src="user.avatarUrl"
              :alt="user.name"
              class="h-20 w-20 rounded-full object-cover"
            />
            <span
              v-else
              class="flex h-20 w-20 items-center justify-center rounded-full bg-primary-container text-2xl font-semibold text-on-primary-container"
            >
              {{ initials }}
            </span>

            <!-- MD3 small FAB (primary-container) -->
            <button
              type="button"
              class="state-layer touch-target absolute -bottom-1 -right-1 flex h-8 w-8 items-center justify-center rounded-lg border-2 border-card bg-primary-container text-on-primary-container shadow disabled:opacity-60 [--touch-slop:-6px]"
              :disabled="uploading"
              :aria-label="uploading ? $t('common.working') : $t('profile.avatar.change')"
              :aria-describedby="describedBy"
              :aria-invalid="invalid"
              @click="fileInput?.click()"
            >
              <MaterialSymbol
                v-if="uploading"
                name="progress_activity"
                :size="14"
                class="animate-spin"
              />
              <MaterialSymbol v-else name="photo_camera" :size="14" />
            </button>
            <input
              :id="id"
              ref="fileInput"
              type="file"
              accept="image/*"
              class="hidden"
              :disabled="uploading"
              :aria-label="$t('profile.avatar.change')"
              :aria-describedby="describedBy"
              :aria-invalid="invalid"
              @change="onPick"
            />
          </div>
        </template>
      </Fieldset>

      <div class="flex-1 text-center sm:text-left">
        <h2 class="text-lg font-semibold text-foreground">{{ user.name }}</h2>
        <div
          class="mt-2 flex flex-wrap items-center justify-center gap-x-4 gap-y-1.5 text-sm text-muted-foreground sm:justify-start"
        >
          <span class="inline-flex items-center gap-1.5">
            <MaterialSymbol name="shield" :size="18" />
            {{ roleLabel(primaryRole, $t) }}
          </span>
          <span class="inline-flex items-center gap-1.5">
            <MaterialSymbol name="mail" :size="18" />
            {{ user.email }}
          </span>
        </div>
      </div>

      <div class="flex flex-wrap justify-center gap-2 sm:justify-end">
        <Badge v-for="role in user.roles" :key="role" variant="muted">{{
          roleLabel(role, $t)
        }}</Badge>
      </div>
    </div>
  </div>
</template>
